@echo off
REM Adlocaite Broadsign Integration - Build Script (Windows)
REM Creates .x-html-package file for Broadsign Control

echo Building Adlocaite Broadsign Integration Package...
echo.

REM Check if config.js exists
if not exist "package\js\config.js" (
  echo ERROR: config.js not found!
  echo.
  echo Please create config.js from the template:
  echo   copy package\js\config.example.js package\js\config.js
  echo.
  echo Then edit config.js and add your API key.
  exit /b 1
)

REM Check if API key is configured (only the apiKey line, not comments)
findstr /R /C:"^ *apiKey:.*pub_xxxx" "package\js\config.js" >nul
if %errorlevel% equ 0 (
  echo WARNING: API key not configured in config.js
  echo Make sure to update your API key before deploying to production.
  echo.
)

REM Clean previous build
if exist "adlocaite-broadsign.x-html-package" (
  echo Cleaning previous build...
  del /F /Q "adlocaite-broadsign.x-html-package"
)

REM Check if package.json exists
if not exist "package.json" (
  echo ERROR: package.json not found
  exit /b 1
)

REM Generate version.js (single source of truth: package.json), like build.sh
echo Generating package\js\version.js from package.json...
set VERSION=
for /f "tokens=2 delims=:," %%a in ('findstr /C:"\"version\"" package.json') do set VERSION=%%a

REM Validate version extraction
if not defined VERSION (
  echo ERROR: Failed to extract version from package.json
  exit /b 1
)
set VERSION=%VERSION:"=%
set VERSION=%VERSION: =%
if "%VERSION%"=="" (
  echo ERROR: Failed to extract version from package.json
  exit /b 1
)

(
  echo // AUTO-GENERATED by build.bat from package.json - DO NOT EDIT
  echo // Regenerated on every build, gitignored. To change the version, edit package.json.
  echo window.ADLOCAITE_VERSION = '%VERSION%';
) > "package\js\version.js"
if not exist "package\js\version.js" (
  echo ERROR: Failed to write package\js\version.js
  exit /b 1
)
echo   Version %VERSION% written to package\js\version.js

REM Check if 7-Zip is available
where 7z >nul 2>nul
if %errorlevel% neq 0 (
  echo ERROR: 7-Zip not found!
  echo.
  echo Please install 7-Zip from https://www.7-zip.org/
  echo Or run build.sh from Git Bash
  exit /b 1
)

REM Create package (same files as build.sh: index.html, js\*.js, css\*.css)
echo Creating package...
cd package
7z a -tzip ..\adlocaite-broadsign.x-html-package index.html js\*.js css\*.css -x!.DS_Store
set ZIP_EXIT=%errorlevel%
cd ..
if %ZIP_EXIT% neq 0 (
  echo ERROR: 7-Zip failed with exit code %ZIP_EXIT%
  exit /b 1
)

REM Check if package was created
if exist "adlocaite-broadsign.x-html-package" (
  echo.
  echo Package created successfully!
  echo.
  echo Package details:
  echo   File: adlocaite-broadsign.x-html-package
  echo.
  echo Next steps:
  echo   1. Open Broadsign Control Administrator
  echo   2. Navigate to Library ^> Ad Copies
  echo   3. Click Upload and select the .x-html-package file
  echo   4. Assign the ad copy to your campaign
  echo.
  echo Testing:
  echo   Enable debug mode in config.js to see detailed logs
  echo   Check Broadsign Player logs for troubleshooting
  echo.
) else (
  echo ERROR: Package creation failed!
  exit /b 1
)


